### ISSUE TITLE
Optional button modules causing bassplate build fail

### ISSUE THREAD

**Issue by brianzelip** [basscss/bassplate#11]
When you uncomment all optional basscss modules in bassplate's `src/base.css` in order to include them in the build, `$ npm start` fails. It's been happening for at least a month.

I'm not sure what the actual problem is, but i've narrowed down the list of modules that throw the error:

``` css
/*@import 'basscss-color-buttons';*/
/*@import 'basscss-button-blue';*/
/*@import 'basscss-button-blue-outline';*/
/*@import 'basscss-button-gray';*/
/*@import 'basscss-button-light-gray';*/
/*@import 'basscss-button-red';*/
```

Here is the npm error message:

``` bash
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "minify:css"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! bassplate@4.0.0 minify:css: `cssnext -c src/base.css css/base.min.css`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the bassplate@4.0.0 minify:css script 'cssnext -c src/base.css css/base.min.css'.
npm ERR! This is most likely a problem with the bassplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cssnext -c src/base.css css/base.min.css
npm ERR! You can get their info via:
npm ERR!     npm owner ls bassplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/brianzelip/WebProjects/leaflet-map-sandbox/testing_customization/npm-debug.log
```

And here is the content of `npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'minify:css' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'preminify:css', 'minify:css', 'postminify:css' ]
6 info preminify:css bassplate@4.0.0
7 info minify:css bassplate@4.0.0
8 verbose unsafe-perm in lifecycle true
9 info bassplate@4.0.0 Failed to exec minify:css script
10 verbose stack Error: bassplate@4.0.0 minify:css: `cssnext -c src/base.css css/base.min.css`
10 verbose stack Exit status 2
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid bassplate@4.0.0
12 verbose cwd /Users/brianzelip/WebProjects/leaflet-map-sandbox
13 error Darwin 14.4.0
14 error argv "node" "/usr/local/bin/npm" "run" "minify:css"
15 error node v0.12.4
16 error npm  v2.10.1
17 error code ELIFECYCLE
18 error bassplate@4.0.0 minify:css: `cssnext -c src/base.css css/base.min.css`
18 error Exit status 2
19 error Failed at the bassplate@4.0.0 minify:css script 'cssnext -c src/base.css css/base.min.css'.
19 error This is most likely a problem with the bassplate package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     cssnext -c src/base.css css/base.min.css
19 error You can get their info via:
19 error     npm owner ls bassplate
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by jxnblk** [comment]
Thanks!

Just taking a look at this now. It might be related to older versions of Basscss using https://github.com/reworkcss/rework-plugin-colors, which isn't valid CSS syntax. I'm not sure if there is an equivalent for PostCSS, but I should patch those modules to support the `color()` syntax.

**Comment by jxnblk** [comment]
For now, I'd recommend using the new button modules if possible.

**Comment by jxnblk** [comment]
I've removed the deprecated button modules, so this shouldn't be an issue any longer. Let me know if you're still encountering problems.
